services:
  minio:
    image: minio/minio:${MINIO_VERSION}
    container_name: boilerplate-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ./docker/minio/data:/data
    command: server /data --console-address ":9001"
  minio-init:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mc alias set local http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD};
      mc mb local/boilerplate --ignore-existing;
      mc anonymous set download local/boilerplate/avatar;
      mc anonymous set download local/boilerplate/temp/avatar;
      exit 0;
      "